//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSEProtocolSpacewire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSEProtocolSpacewire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSEProtocolSpacewire", typeof(EGSEProtocolSpacewire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра слишком большой!.
        /// </summary>
        internal static string eBigSpacewireData {
            get {
                return ResourceManager.GetString("eBigSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire меньше 4 байт!.
        /// </summary>
        internal static string eSmallSpacewireData {
            get {
                return ResourceManager.GetString("eSmallSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 10 байт!.
        /// </summary>
        internal static string eSmallSpacewireIcdData {
            get {
                return ResourceManager.GetString("eSmallSpacewireIcdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 16 байт!.
        /// </summary>
        internal static string eSmallSpacewireTkData {
            get {
                return ResourceManager.GetString("eSmallSpacewireTkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 16 байт!.
        /// </summary>
        internal static string eSmallSpacewireTmData {
            get {
                return ResourceManager.GetString("eSmallSpacewireTmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire obt некорректен!.
        /// </summary>
        internal static string eSpacewireObtData {
            get {
                return ResourceManager.GetString("eSpacewireObtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра timeTick некорректен!.
        /// </summary>
        internal static string eTickTimeSpacewireData {
            get {
                return ResourceManager.GetString("eTickTimeSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный кадр spacewire!.
        /// </summary>
        internal static string eUnknowSpacewireData {
            get {
                return ResourceManager.GetString("eUnknowSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},{1},{2},0x{3:X},{4},{5},{6}].
        /// </summary>
        internal static string stIcdString {
            get {
                return ResourceManager.GetString("stIcdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок пакета: Идентификатор пакета[Номер версии:{0}, Тип:{1}, Флаг заголовка данных:{2}, APID:0x{3:X}] Поле контроля последовательности[Флаг сегментации:{4}, Счетчик последовательности:{5}, Длина поля данных:{6}].
        /// </summary>
        internal static string stIcdStringExt {
            get {
                return ResourceManager.GetString("stIcdStringExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0},0x{1:X},{2},{3}].
        /// </summary>
        internal static string stSptpString {
            get {
                return ResourceManager.GetString("stSptpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок sptp[Назначение:{0},Протокол:0x{1:X},Тип:{2},Инициатор:{3}].
        /// </summary>
        internal static string stSptpStringExt {
            get {
                return ResourceManager.GetString("stSptpStringExt", resourceCulture);
            }
        }
    }
}
