//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSEDeviceBUK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSEDeviceBUK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSEDeviceBUK", typeof(EGSEDeviceBUK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlValuesList не должны быть равны null!.
        /// </summary>
        internal static string eNotAssigned {
            get {
                return ResourceManager.GetString("eNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость передачи по USB: {0}/с.
        /// </summary>
        internal static string stDeviceSpeed {
            get {
                return ResourceManager.GetString("stDeviceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трафик: {0}.
        /// </summary>
        internal static string stDeviceTrafic {
            get {
                return ResourceManager.GetString("stDeviceTrafic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buk.
        /// </summary>
        internal static string stDevLogName {
            get {
                return ResourceManager.GetString("stDevLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hsibuk.
        /// </summary>
        internal static string stHsiLogName {
            get {
                return ResourceManager.GetString("stHsiLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}, на позиции: {2}).
        /// </summary>
        internal static string stOnErrorUSBMsg {
            get {
                return ResourceManager.GetString("stOnErrorUSBMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdbuk.
        /// </summary>
        internal static string stSdLogName {
            get {
                return ResourceManager.GetString("stSdLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БКП (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBkp {
            get {
                return ResourceManager.GetString("stShowLogicBkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БУК (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBuk {
            get {
                return ResourceManager.GetString("stShowLogicBuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имитатор БМ-4 (БУСК, БУНД) (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBusk {
            get {
                return ResourceManager.GetString("stShowLogicBusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имитатор БУК (для БМ-4) (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicBusk {
            get {
                return ResourceManager.GetString("stShowSimLogicBusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to БУК (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicSD1 {
            get {
                return ResourceManager.GetString("stShowSimLogicSD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НП2 (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicSD2 {
            get {
                return ResourceManager.GetString("stShowSimLogicSD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spacewirebuk.
        /// </summary>
        internal static string stSpacewireLogName {
            get {
                return ResourceManager.GetString("stSpacewireLogName", resourceCulture);
            }
        }
    }
}
