//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSECyclogramCommandBUK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSECyclogramCommandBUK() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSECyclogramCommandBUK", typeof(EGSECyclogramCommandBUK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 арг.: {0}.
        /// </summary>
        internal static string eArg1 {
            get {
                return ResourceManager.GetString("eArg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 арг.: {0}.
        /// </summary>
        internal static string eArg2 {
            get {
                return ResourceManager.GetString("eArg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 арг.: {0}.
        /// </summary>
        internal static string eArg3 {
            get {
                return ResourceManager.GetString("eArg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 арг.: {0}.
        /// </summary>
        internal static string eArg4 {
            get {
                return ResourceManager.GetString("eArg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 арг.: {0}.
        /// </summary>
        internal static string eArg5 {
            get {
                return ResourceManager.GetString("eArg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 арг.: {0}.
        /// </summary>
        internal static string eArg6 {
            get {
                return ResourceManager.GetString("eArg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to обнаружен дублирующий аргумент {0}.
        /// </summary>
        internal static string eArgUnique {
            get {
                return ResourceManager.GetString("eArgUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ошибка в посылке ({0}).
        /// </summary>
        internal static string eBadPackage {
            get {
                return ResourceManager.GetString("eBadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибочное количество аргументов команды!.
        /// </summary>
        internal static string eParamCount {
            get {
                return ResourceManager.GetString("eParamCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружены дублирующие аргументы!.
        /// </summary>
        internal static string eUnique {
            get {
                return ResourceManager.GetString("eUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to должен быть {0}.
        /// </summary>
        internal static string stNeedBy {
            get {
                return ResourceManager.GetString("stNeedBy", resourceCulture);
            }
        }
    }
}
