//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSEDeviceBUK {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSEDeviceBUK() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSEDeviceBUK", typeof(EGSEDeviceBUK).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер посылки более 250 байт!.
        /// </summary>
        internal static string eBadDataSendMsg {
            get {
                return ResourceManager.GetString("eBadDataSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ControlValuesList не должны быть равны null!.
        /// </summary>
        internal static string eNotAssigned {
            get {
                return ResourceManager.GetString("eNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость передачи по USB: {0}/с.
        /// </summary>
        internal static string stDeviceSpeed {
            get {
                return ResourceManager.GetString("stDeviceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трафик: {0}.
        /// </summary>
        internal static string stDeviceTrafic {
            get {
                return ResourceManager.GetString("stDeviceTrafic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на buk.
        /// </summary>
        internal static string stDevLogName {
            get {
                return ResourceManager.GetString("stDevLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на hsibuk.
        /// </summary>
        internal static string stHsiLogName {
            get {
                return ResourceManager.GetString("stHsiLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} ({1}, на позиции: {2}).
        /// </summary>
        internal static string stOnErrorUSBMsg {
            get {
                return ResourceManager.GetString("stOnErrorUSBMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sdbuk.
        /// </summary>
        internal static string stSdLogName {
            get {
                return ResourceManager.GetString("stSdLogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БКП (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBkp {
            get {
                return ResourceManager.GetString("stShowLogicBkp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУК (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBuk {
            get {
                return ResourceManager.GetString("stShowLogicBuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имитатор БМ-4 (БУСК, БУНД) (адрес: {0}).
        /// </summary>
        internal static string stShowLogicBusk {
            get {
                return ResourceManager.GetString("stShowLogicBusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имитатор БУК (для БМ-4) (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicBusk {
            get {
                return ResourceManager.GetString("stShowSimLogicBusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на БУК (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicSD1 {
            get {
                return ResourceManager.GetString("stShowSimLogicSD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НП2 (адрес: {0}).
        /// </summary>
        internal static string stShowSimLogicSD2 {
            get {
                return ResourceManager.GetString("stShowSimLogicSD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на spacewirebuk.
        /// </summary>
        internal static string stSpacewireLogName {
            get {
                return ResourceManager.GetString("stSpacewireLogName", resourceCulture);
            }
        }
    }
}
