//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSEProtocolSpacewire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSEProtocolSpacewire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSEProtocolSpacewire", typeof(EGSEProtocolSpacewire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра слишком большой!.
        /// </summary>
        internal static string eBigSpacewireData {
            get {
                return ResourceManager.GetString("eBigSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire меньше 4 байт!.
        /// </summary>
        internal static string eSmallSpacewireData {
            get {
                return ResourceManager.GetString("eSmallSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 10 байт!.
        /// </summary>
        internal static string eSmallSpacewireIcdData {
            get {
                return ResourceManager.GetString("eSmallSpacewireIcdData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 16 байт!.
        /// </summary>
        internal static string eSmallSpacewireTkData {
            get {
                return ResourceManager.GetString("eSmallSpacewireTkData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire icd меньше 16 байт!.
        /// </summary>
        internal static string eSmallSpacewireTmData {
            get {
                return ResourceManager.GetString("eSmallSpacewireTmData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра spacewire obt некорректен!.
        /// </summary>
        internal static string eSpacewireObtData {
            get {
                return ResourceManager.GetString("eSpacewireObtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер кадра timeTick некорректен!.
        /// </summary>
        internal static string eTickTimeSpacewireData {
            get {
                return ResourceManager.GetString("eTickTimeSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестный кадр spacewire!.
        /// </summary>
        internal static string eUnknowSpacewireData {
            get {
                return ResourceManager.GetString("eUnknowSpacewireData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ({0}d) [{1}] Ошибка: {2}.
        /// </summary>
        internal static string stErrorMsgToString {
            get {
                return ResourceManager.GetString("stErrorMsgToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7} - ICD[V:{0:X},T:{1:X},F:{2:X},A:{3:X},S:{4:X},C:{5}d,{6}d].
        /// </summary>
        internal static string stIcdString {
            get {
                return ResourceManager.GetString("stIcdString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7} - ICD(Идентификатор пакета[Номер версии:{0}, Тип:{1}, Флаг заголовка данных:{2}, APID:0x{3:X}] - Поле контроля последовательности[Флаг сегментации:{4}, Счетчик последовательности:{5}, Длина поля данных:{6}]).
        /// </summary>
        internal static string stIcdStringExt {
            get {
                return ResourceManager.GetString("stIcdStringExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ({0}d) {1} [{2}].
        /// </summary>
        internal static string stSptpMsgToString {
            get {
                return ResourceManager.GetString("stSptpMsgToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPTP[{0:X},{1:X},{2:X},{3:X}].
        /// </summary>
        internal static string stSptpString {
            get {
                return ResourceManager.GetString("stSptpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPTP(Идентификатор пакета[Назначение:{0},Протокол:0x{1:X},Тип:{2},Инициатор:{3}]).
        /// </summary>
        internal static string stSptpStringExt {
            get {
                return ResourceManager.GetString("stSptpStringExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ({0}d) {1} [{2}] {3}.
        /// </summary>
        internal static string stTkMsgToString {
            get {
                return ResourceManager.GetString("stTkMsgToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6} - TK[H:{0:X},P:{1:X},Q:{2:X},S:{3:X},s:{4:X},R:{5:X}].
        /// </summary>
        internal static string stTkString {
            get {
                return ResourceManager.GetString("stTkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {6} - TK(Флаг вторичного заголовка CCSDS:{0},Номер версии ТМ-пакета PUS:{1},Тип квитирования:{2},Тип сервиса:{3},Подтип сервиса:{4},Резерв:{5}).
        /// </summary>
        internal static string stTkStringExt {
            get {
                return ResourceManager.GetString("stTkStringExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : ({0}d) {1} [{2}] {3}.
        /// </summary>
        internal static string stTmMsgToString {
            get {
                return ResourceManager.GetString("stTmMsgToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7} - TM[R:{0:X},V:{1:X},P:{2:X},S:{3:X},s:{4:X},R:{5:X},{6}].
        /// </summary>
        internal static string stTmString {
            get {
                return ResourceManager.GetString("stTmString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {7} - TM(Резерв:{0},Номер версии ТМ-пакета PUS:{1},Резерв:{2},Тип сервиса:{3},Подтип сервиса:{4},Резерв (п/о):{5},Время:{6}).
        /// </summary>
        internal static string stTmStringExt {
            get {
                return ResourceManager.GetString("stTmStringExt", resourceCulture);
            }
        }
    }
}
