//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EGSEProtocolUSB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EGSEProtocolUSB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wpf.EGSEProtocolUSB", typeof(EGSEProtocolUSB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адресный байт больше 255.
        /// </summary>
        internal static string eBadAddr {
            get {
                return ResourceManager.GetString("eBadAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC8 кадра расчитан неверно.
        /// </summary>
        internal static string eBadCRC {
            get {
                return ResourceManager.GetString("eBadCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRC8 заголовка расчитан неверно.
        /// </summary>
        internal static string eBadHeadCRC {
            get {
                return ResourceManager.GetString("eBadHeadCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен максимальный размер кадра.
        /// </summary>
        internal static string eMaxFrameSize {
            get {
                return ResourceManager.GetString("eMaxFrameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После 0x5E отсутствует 0x4D.
        /// </summary>
        internal static string eMissing4D {
            get {
                return ResourceManager.GetString("eMissing4D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to После сообщения не встретился 0x5E.
        /// </summary>
        internal static string eMissing5E {
            get {
                return ResourceManager.GetString("eMissing5E", resourceCulture);
            }
        }
    }
}
